// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const images = [
  { image: '../../public/ImageGathering/blue1.jpg', type: 'blue' },
  { image: '../../public/ImageGathering/blue2.png', type: 'blue' },
  { image: '../../public/ImageGathering/blue3.jpg', type: 'blue' },
  { image: '../../public/ImageGathering/blue4.png', type: 'blue' },
  { image: '../../public/ImageGathering/blue5.png', type: 'blue' },
  { image: '../../public/ImageGathering/blue6.jpg', type: 'blue' },
  { image: '../../public/ImageGathering/blue7.jpg', type: 'blue' },
  { image: '../../public/ImageGathering/blue8.jpg', type: 'blue' },
  { image: '../../public/ImageGathering/blue9.png', type: 'blue' },
  { image: '../../public/ImageGathering/grey1.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey2.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey3.png', type: 'grey' },
  { image: '../../public/ImageGathering/grey4.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey5.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey6.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey7.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey8.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/grey9.jpg', type: 'grey' },
  { image: '../../public/ImageGathering/noncompany1.png', type: 'not blue' },
  {
    image: '../../public/ImageGathering/noncompany2.png',
    type: 'not blue',
  },
  { image: '../../public/ImageGathering/noncompany3.png', type: 'not blue' },
  {
    image: '../../public/ImageGathering/noncompany4.png',
    type: 'not blue',
  },
  { image: '../../public/ImageGathering/noncompany5.jpg', type: 'not blue' },
  { image: '../../public/ImageGathering/noncompany6.png', type: 'not blue' },
  { image: '../../public/ImageGathering/noncompany7.jpg', type: 'not blue' },
  { image: '../../public/ImageGathering/noncompany8.png', type: 'not blue' },
  {
    image: '../../public/ImageGathering/noncompany9.jpg',
    type: 'not blue',
  },
  { image: '../../public/ImageGathering/trueblack1.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack2.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack3.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack4.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack5.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack6.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack7.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack8.jpg', type: 'black' },
  { image: '../../public/ImageGathering/trueblack9.jpg', type: 'black' },
]
