export const imageset = [
    [
        {image: "../../CaptchaImages/A1.png", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A2.png", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A3.png", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A4.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A5.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A6.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A7.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A8.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A9.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/A10.jpg", type: 'AI generated eye'},
        {image: "../../CaptchaImages/H1.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H2.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H3.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H4.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H5.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H6.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H7.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H8.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/H9.jpg", type: 'human eye'},
        {image: "../../CaptchaImages/Camera5.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera6.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera8.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera9.jpg", type: 'security camera'}
    ], 
    [
        {image: "../../CaptchaImages/Corridor1.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor2.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor3.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor4.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor5.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor6.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor7.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor8.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor9.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor10.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Corridor11.jpg", type: 'corridor'},
        {image: "../../CaptchaImages/Elevator1.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator2.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator3.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator4.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator5.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator6.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator7.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator8.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator9.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator10.jpg", type: 'elevator'},
        {image: "../../CaptchaImages/Elevator11.jpg", type: 'elevator'}, 
    ],
    [
        {image: "../../CaptchaImages/Camera1.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera2.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera3.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera4.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera5.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera6.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera7.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera8.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/Camera9.jpg", type: 'security camera'},
        {image: "../../CaptchaImages/TrafficLight1.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight2.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight3.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight4.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight5.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight6.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight7.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight8.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight9.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight10.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/TrafficLight11.jpg", type: 'traffic light'},
        {image: "../../CaptchaImages/Crossing8.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing9.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing10.jpg", type: 'pedestrian crossing'}
    ],
    [
        {image: "../../CaptchaImages/Crossing1.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing2.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing3.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing4.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing5.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing6.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing7.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing8.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing9.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing10.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Crossing11.jpg", type: 'pedestrian crossing'},
        {image: "../../CaptchaImages/Zebra1.png", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra2.png", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra3.png", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra4.png", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra5.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra6.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra7.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra8.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra9.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra10.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra11.jpg", type: 'zebra'},
        {image: "../../CaptchaImages/Zebra12.jpg", type: 'zebra'}
    ]
]

